### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kohei306** [nazarimilad/open-intelligence-backend#5]
Hi !
I saw you implementation and you are executing the OCR to entire table. I was wondering if it is better or worse than doing OCR one by one for each cell. I am interested in your reasoning.

**Comment by nazarimilad** [comment]
Hey! 

The OCR processing is delegated to Tesseract OCR. And since Tesseract OCR was mainly developed for document OCR, and not simply word by word OCR, it performs better when applied to a whole document or table in this case.

You can run Tesseract in different modes ([page segmentation modes](https://pyimagesearch.com/2021/11/15/tesseract-page-segmentation-modes-psms-explained-how-to-improve-your-ocr-accuracy/)) though. PSM 4 and 6 gave me the most accurate results.

Although Tesseract OCR is a good choice for OCR, I would recommend trying out [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR). It has several advantages, such as: multi lingual support, layout analysis, table recognition, etc.

**Comment by kohei306** [comment]
Thanks for your reply! I see, I will try the PaddleOCR!

**Comment by nazarimilad** [comment]
You're welcome :)
